### ISSUE TITLE
Переименование некоторых значений

### ISSUE THREAD

**Issue by Namemkzaza** [WikiCharts/wikicharts.github.io#2]
Как вам вариант переименовать значения "Страты" и "Радикальный центризм"? Предлагаю варианты "Стратификация"/"Эпистократия" в качестве альтернативы "Стратам", и "Смесь взглядов" в качестве  альтернативы "Радикальному центризму". Как по мне, эти варианты будут звучать немного более логично и понятно, нежели чем текущие.

**Comment by WikiCharts** [comment]
Спасибо за идею! Насчет Радикального центризма я согласен, можно переименовать. Насчет Страт - я подумаю, но как по мне, "Эпистократия" тут не очень подходит. Я погуглил, и выяснил, что этот термин примерно означает "власть знающих" или "власть доверенных". А в тесте Страты скорее означают "власть статусных", "власть активных".

**Comment by Namemkzaza** [comment]
Можно "Страты" переименовать в "Меритократию" - режим, основанный на выдвижении к власти участников, обладающих способностями или наибольшими заслугами; власть наиболее достойных.

То есть, Меритократия в данном тесте всё еще отличается от авторитарных режимов (Автократия, Олигархия), при которых вся власть целиком сосредоточена в руках очень узкой группы людей (или только в руках одного администратора).
Как сказано в описании этой идеологии: "Мнение обычных пользователей может учитываться, но не так сильно, как мнение привилегированных участников". Таким образом, большая часть власти (но не вся власть) сосредоточена в руках не слишком большой группы участников (но более большой, чем при олигархии, например). Но Меритократия всё ещё достаточно элитарна и зачастую не слишком демократична.

**Comment by WikiCharts** [comment]
Окей, Страты были переименованы в Меритократию. Наверное, так действительно будет лучше и понятнее
